name: Build APKs

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches:
      - master
      - dev
env: 
  TZ: Asia/Shanghai

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get tags
      id: get_head
      run: |
        echo "head=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Set versionCode
      run: |
        sed -i "s/versionCode .*/versionCode $(date +%Y%m%d)/" app/build.gradle

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
        
    - name: Clean Gradle Cache
      uses: gradle/gradle-build-action@v3
      with:
        gradle-home-cache-cleanup: true
        
    - name: Build Release APK
      run: |
        ./gradlew --no-daemon --no-configuration-cache -q app:assembleRelease

    - name: Display files in directory
      run: |
        ls app/build/outputs/apk/release

    - uses: d2184/android-sign@main
      name: Sign app APK
      with:
        releaseDirectory: app/build/outputs/apk/release
        output: app/build/outputs/apk/release
        alias: ${{ secrets.KEY_ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        signingKeyBase64: ${{ secrets.KEYSTORE_CONTENT }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "33.0.0"

    - name: Rename Apks
      run: |
        mkdir -p APKs
        mv app/build/outputs/apk/release/app-release-unsigned-signed.apk APKs/box-manager-${{ steps.get_head.outputs.head }}-alpha.apk

    - uses: actions/upload-artifact@v4
      if: ${{ github.ref_name == 'master' && github.event_name == 'pull_request' }}
      with:
        name: signed_apps
        path: APKs

    - name: Delete current Prerelease-alpha assets
      if: ${{ github.ref_name == 'master' && github.event_name != 'pull_request' }}
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: Prerelease-Alpha
        assets: "*.apk"
        fail-if-no-assets: false
        fail-if-no-release: false

    - name: Upload Prerelease-alpha
      if: ${{ github.ref_name == 'master' && github.event_name != 'pull_request' }}
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Prerelease-Alpha
        release_name: Prerelease-Alpha
        file: "APKs/*.apk"
        prerelease: true
        file_glob: true
